### ISSUE TITLE
Dynamically set match names

### ISSUE THREAD

**Issue by awest25** [bruin-tennis-consulting/match-manager#113]
To improve consistency and lower the burden for people uploading matches, everywhere that we currently use `data.name`, replace it with a standard string format using the other properties found in the document of each `match`.

Temporarily use the following format:

```text
Hance vs. Ratliff - UCLA vs. Ohio State - 02-04-2024
```

**Comment by krish1925** [comment]
@Fredenck I remember bundling this issue into another PR and was discussing this with Alex, the functionality of this is in upload.js where I used regex to extract and have the player/match name in the specified format:     const matchName = `${players.client.firstName} ${players.client.lastName} ${teams.clientTeam} vs. ${players.opponent.firstName} ${players.opponent.lastName} ${teams.opponentTeam}`
