### ISSUE TITLE
Add logout button

### ISSUE THREAD

**Issue by awest25** [bruin-tennis-consulting/match-manager#194]
Add a blue "logout" button to the top right of the homepage.

It may be useful to look at `import { onAuthStateChanged, signOut } from 'firebase/auth'` in `app/components/AuthWrapper.js`

The following  image shows what our "login" button looks like. It should look the same but change to "logout" when the user is logged into an account.

<img width="1499" alt="Screenshot 2024-10-14 at 11 21 08 PM" src="https://github.com/user-attachments/assets/f26452b5-906d-4041-9554-2af15cffe319">

### Development
Note that there is already a branch created for this issue (on the right). It is branched from branch `development`. This is our new "main" branch for this sprint but it's not publicly accessible. So even if you aren't completely done, please merge frequently into `development` so everyone else can see your changes. We will merge it into `main` to be hosted when all features in the sprint are done.

When you start working on the issue, immediately create a PR against the `development` branch and link this issue. This way we can see your live progress.

**Comment by Fredenck** [comment]
closed in #228
