### ISSUE TITLE
Fix auto redeploy on push GH action

### ISSUE THREAD

**Issue by awest25** [bruin-tennis-consulting/match-manager#200]
In the meanwhile, manually run `firebase deploy` in the CLI on push.

Our GH action doesn't work, seems like an authentication issue related (potentially) to firebase functions.

Log into Firebase (reach out if you need creds), then go to the project -> settings -> users and permissions -> advanced permission settings and here you should see a list of accounts or something. The github action account doesn't work. Tried adding permissions but wasn't able to figure it out.

Once you make a change, you can test to see if the action works by going to the GH action menu, clicking on the latest failed deploy, and clicking the little rerun button.

Here's what the error in the GH log says:
```
The caller does not have permission
firebaseextensions.instances.list
```

**Comment by ritzz26** [comment]
@Fredenck @awest25 is this fixed now?
