### ISSUE TITLE
Adhere to Published Field

### ISSUE THREAD

**Issue by Fredenck** [bruin-tennis-consulting/match-manager#250]
For a match:

```
if published: 
  show on dashboard
else:
  do not show on dashboard.
```

Functionality/Idea: we don't want in-progress tagged matches to be shown on the dashboard (ie 5 copies of the same match). By default, uploaded matches should be unpublished. If a tagger clicks "Publish" on the tagging page, the flag flips and the match should be visible on Dashboard.

**Comment by Fredenck** [comment]
sorry krish, I did this ! :(

**Comment by krish1925** [comment]
lol no worries^^^
